import React from 'react';
import { useLocation } from 'wouter';
import { ArrowLeft, CheckCircle2, BookOpen, Video, AlertCircle, TrendingUp, BarChart3, Zap } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { DASHBOARD_HOME_PATH, navigateToDashboardMenu } from '@/lib/navigation';
import { VideoPlaylist } from '@/components/VideoTutorial';

export default function GettingStarted() {
  const [, setLocation] = useLocation();

  const sections = [
    {
      id: 'signals',
      title: 'Understanding Trading Signals',
      icon: TrendingUp,
      description: 'Learn how Stock Predictor generates buy, sell, and hold signals',
      content: (
        <div className="space-y-4">
          <div>
            <h4 className="font-semibold mb-2 flex items-center gap-2">
              <CheckCircle2 className="h-4 w-4 text-green-500" />
              What are trading signals?
            </h4>
            <p className="text-sm text-muted-foreground">
              Trading signals are recommendations generated by technical analysis to help you decide when to buy, sell, or hold a stock. Our signals are based on multiple technical indicators working together to identify potential trading opportunities.
            </p>
          </div>

          <div>
            <h4 className="font-semibold mb-2 flex items-center gap-2">
              <CheckCircle2 className="h-4 w-4 text-green-500" />
              How are signals generated?
            </h4>
            <p className="text-sm text-muted-foreground mb-2">
              Stock Predictor analyzes each stock using four key technical indicators:
            </p>
            <ul className="space-y-2 text-sm text-muted-foreground">
              <li className="flex gap-2">
                <span className="font-medium text-foreground min-w-20">RSI:</span>
                <span>Relative Strength Index measures momentum (0-100). Above 70 = overbought, below 30 = oversold.</span>
              </li>
              <li className="flex gap-2">
                <span className="font-medium text-foreground min-w-20">MACD:</span>
                <span>Moving Average Convergence Divergence tracks trend momentum. Positive = bullish, negative = bearish.</span>
              </li>
              <li className="flex gap-2">
                <span className="font-medium text-foreground min-w-20">Bollinger Bands:</span>
                <span>Shows volatility and price extremes. Price near upper band = overbought, near lower = oversold.</span>
              </li>
              <li className="flex gap-2">
                <span className="font-medium text-foreground min-w-20">SMA:</span>
                <span>Simple Moving Average identifies trend direction. Price above SMA = uptrend, below = downtrend.</span>
              </li>
            </ul>
          </div>

          <div>
            <h4 className="font-semibold mb-2 flex items-center gap-2">
              <CheckCircle2 className="h-4 w-4 text-green-500" />
              What does confidence mean?
            </h4>
            <p className="text-sm text-muted-foreground">
              Confidence (25-100%) shows how strongly the indicators agree on a direction. Higher confidence = more indicators aligned. We recommend focusing on signals with 60%+ confidence for better reliability.
            </p>
          </div>

          <Alert>
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>
              <strong>Important:</strong> Signals are generated daily using end-of-day market data. They work best for swing trades (3-5 day holds), not day trading. Past performance does not guarantee future results.
            </AlertDescription>
          </Alert>
        </div>
      ),
    },
    {
      id: 'watchlist',
      title: 'Building Your Watchlist',
      icon: BookOpen,
      description: 'Create a personalized list of stocks to monitor',
      content: (
        <div className="space-y-4">
          <div>
            <h4 className="font-semibold mb-2 flex items-center gap-2">
              <CheckCircle2 className="h-4 w-4 text-green-500" />
              How to add stocks to your watchlist
            </h4>
            <ol className="space-y-2 text-sm text-muted-foreground list-decimal list-inside">
              <li>Go to the Signals Dashboard</li>
              <li>Click "Add Stock" or search for a ticker (e.g., AAPL, MSFT, TSLA)</li>
              <li>The stock will appear in your watchlist with the latest signal</li>
              <li>You can add up to 50 stocks to track</li>
            </ol>
          </div>

          <div>
            <h4 className="font-semibold mb-2 flex items-center gap-2">
              <CheckCircle2 className="h-4 w-4 text-green-500" />
              What information do you see?
            </h4>
            <p className="text-sm text-muted-foreground mb-2">For each stock in your watchlist:</p>
            <ul className="space-y-1 text-sm text-muted-foreground list-disc list-inside">
              <li>Current price and 24-hour change</li>
              <li>Latest signal (Buy/Sell/Hold) with confidence score</li>
              <li>When the signal was last updated</li>
              <li>Technical indicator values (RSI, MACD, etc.)</li>
            </ul>
          </div>

          <div>
            <h4 className="font-semibold mb-2 flex items-center gap-2">
              <CheckCircle2 className="h-4 w-4 text-green-500" />
              Tips for building a good watchlist
            </h4>
            <ul className="space-y-2 text-sm text-muted-foreground list-disc list-inside">
              <li>Start with 5-10 stocks you're familiar with</li>
              <li>Mix different sectors (tech, finance, healthcare, etc.)</li>
              <li>Include large-cap (AAPL, MSFT) and smaller stocks</li>
              <li>Review your watchlist daily for new signals</li>
            </ul>
          </div>
        </div>
      ),
    },
    {
      id: 'simulator',
      title: 'Using the Paper Trading Simulator',
      icon: BarChart3,
      description: 'Practice trading with virtual money, no real capital at risk',
      content: (
        <div className="space-y-4">
          <div>
            <h4 className="font-semibold mb-2 flex items-center gap-2">
              <CheckCircle2 className="h-4 w-4 text-green-500" />
              What is paper trading?
            </h4>
            <p className="text-sm text-muted-foreground">
              Paper trading (also called "simulator trading" or "virtual trading") lets you practice trading strategies with simulated money. No real capital is at risk. It's the perfect way to test signals and build confidence before trading with real money.
            </p>
          </div>

          <div>
            <h4 className="font-semibold mb-2 flex items-center gap-2">
              <CheckCircle2 className="h-4 w-4 text-green-500" />
              How to place a trade
            </h4>
            <ol className="space-y-2 text-sm text-muted-foreground list-decimal list-inside">
              <li>Go to Trading Simulator and select a portfolio</li>
              <li>Enter a stock ticker (e.g., AAPL)</li>
              <li>Enter the quantity of shares you want to buy/sell</li>
              <li>The live price will auto-load (or enter manually)</li>
              <li>Click "Buy" or "Sell" to execute the trade</li>
            </ol>
          </div>

          <div>
            <h4 className="font-semibold mb-2 flex items-center gap-2">
              <CheckCircle2 className="h-4 w-4 text-green-500" />
              Understanding simulator costs
            </h4>
            <p className="text-sm text-muted-foreground mb-2">Trades include realistic costs to match real trading:</p>
            <ul className="space-y-1 text-sm text-muted-foreground list-disc list-inside">
              <li><strong>Commission:</strong> 0.1% per trade (realistic broker fee)</li>
              <li><strong>Slippage:</strong> 0.05% price difference (market volatility)</li>
            </ul>
            <p className="text-xs text-muted-foreground mt-2">These costs are deducted from your portfolio value to simulate real trading conditions.</p>
          </div>

          <div>
            <h4 className="font-semibold mb-2 flex items-center gap-2">
              <CheckCircle2 className="h-4 w-4 text-green-500" />
              Tracking your performance
            </h4>
            <p className="text-sm text-muted-foreground mb-2">The simulator shows you:</p>
            <ul className="space-y-1 text-sm text-muted-foreground list-disc list-inside">
              <li>Portfolio Value: Total worth of your positions + cash</li>
              <li>Total Return: Profit/loss in pounds and percentage</li>
              <li>Win Rate: % of closed trades that were profitable</li>
              <li>Open Positions: Stocks you currently hold</li>
              <li>Trade History: All your past trades</li>
            </ul>
          </div>

          <Alert>
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>
              <strong>Remember:</strong> Simulator results don't guarantee real-world performance. Real trading involves emotions, slippage, and market conditions that may differ from the simulator.
            </AlertDescription>
          </Alert>
        </div>
      ),
    },
    {
      id: 'autotrading',
      title: 'Auto-Trading (Premium Feature)',
      icon: Zap,
      description: 'Let the simulator automatically execute signal-based trades',
      content: (
        <div className="space-y-4">
          <div>
            <h4 className="font-semibold mb-2 flex items-center gap-2">
              <CheckCircle2 className="h-4 w-4 text-green-500" />
              What is auto-trading?
            </h4>
            <p className="text-sm text-muted-foreground">
              Auto-trading automatically scans a basket of stocks and executes buy/sell trades based on live signals. Instead of manually watching for signals, the simulator does it for you. This is perfect for testing how a signal-following strategy would perform.
            </p>
          </div>

          <div>
            <h4 className="font-semibold mb-2 flex items-center gap-2">
              <CheckCircle2 className="h-4 w-4 text-green-500" />
              How auto-trading works
            </h4>
            <ol className="space-y-2 text-sm text-muted-foreground list-decimal list-inside">
              <li>Select a portfolio and click "Start Auto-Trading"</li>
              <li>Choose a trading interval (1 day, 3 days, 7 days)</li>
              <li>The simulator scans 25 random stocks from our universe</li>
              <li>For each stock with a strong signal, it places a buy or sell trade</li>
              <li>Trades execute at live market prices with realistic costs</li>
              <li>You can review all auto-executed trades in the history</li>
            </ol>
          </div>

          <div>
            <h4 className="font-semibold mb-2 flex items-center gap-2">
              <CheckCircle2 className="h-4 w-4 text-green-500" />
              Why use auto-trading?
            </h4>
            <ul className="space-y-2 text-sm text-muted-foreground list-disc list-inside">
              <li>Test signal quality without manual intervention</li>
              <li>See how a passive signal-following strategy performs</li>
              <li>Validate the system before trading real money</li>
              <li>No emotions involved - purely mechanical execution</li>
            </ul>
          </div>

          <Badge variant="secondary">Premium Feature</Badge>
          <p className="text-xs text-muted-foreground">Auto-trading is available on paid plans. Free accounts can use manual paper trading.</p>
        </div>
      ),
    },
  ];

  return (
    <div className="min-h-screen bg-background p-4 md:p-8 page-enter">
      <div className="max-w-4xl mx-auto space-y-8">
        {/* Header */}
        <div className="flex items-center justify-between gap-3 mb-8">
          <button
            onClick={() => navigateToDashboardMenu(setLocation)}
            className="flex items-center gap-2 px-3 py-2 text-sm text-slate-300 hover:text-white transition-colors hover:bg-slate-700 rounded-lg"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to menu
          </button>
        </div>

        {/* Title */}
        <div className="space-y-2">
          <h1 className="text-4xl font-bold gradient-text">Getting Started with Stock Predictor</h1>
          <p className="text-lg text-muted-foreground">
            Learn how to use trading signals, build your watchlist, and practice trading with our paper trading simulator.
          </p>
        </div>

        {/* Quick Links */}
        <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4">
          {sections.map((section) => {
            const Icon = section.icon;
            return (
              <button
                key={section.id}
                onClick={() => {
                  const element = document.getElementById(section.id);
                  element?.scrollIntoView({ behavior: 'smooth' });
                }}
                className="flex items-center gap-3 p-3 rounded-lg border border-border hover:border-primary/50 hover:bg-primary/5 transition-colors text-left"
              >
                <Icon className="h-5 w-5 text-primary flex-shrink-0" />
                <div className="min-w-0">
                  <p className="font-medium text-sm">{section.title}</p>
                  <p className="text-xs text-muted-foreground truncate">{section.description}</p>
                </div>
              </button>
            );
          })}
        </div>

        {/* Main Content */}
        <div className="space-y-8">
          {sections.map((section) => {
            const Icon = section.icon;
            return (
              <Card key={section.id} id={section.id} className="premium-card border-0 bg-transparent shadow-none">
                <CardHeader>
                  <div className="flex items-start gap-3">
                    <Icon className="h-6 w-6 text-primary flex-shrink-0 mt-1" />
                    <div>
                      <CardTitle className="text-2xl">{section.title}</CardTitle>
                      <CardDescription className="mt-1">{section.description}</CardDescription>
                    </div>
                  </div>
                </CardHeader>
                <CardContent className="space-y-4">
                  {section.content}
                </CardContent>
              </Card>
            );
          })}
        </div>

        {/* FAQ Section */}
        <Card className="premium-card border-0 bg-transparent shadow-none">
          <CardHeader>
            <CardTitle className="text-2xl">Frequently Asked Questions</CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <div>
              <h4 className="font-semibold mb-2">Are the signals guaranteed to make money?</h4>
              <p className="text-sm text-muted-foreground">
                No. Trading signals are based on technical analysis and historical patterns, but markets are unpredictable. Past performance does not guarantee future results. Always do your own research and manage risk carefully.
              </p>
            </div>

            <div>
              <h4 className="font-semibold mb-2">Can I use real money with the simulator?</h4>
              <p className="text-sm text-muted-foreground">
                No. The simulator uses virtual money only. It's designed for learning and testing strategies. To trade with real money, you'll need to use a real broker like Trading 212, Interactive Brokers, or others.
              </p>
            </div>

            <div>
              <h4 className="font-semibold mb-2">How often are signals updated?</h4>
              <p className="text-sm text-muted-foreground">
                Signals are generated once per day using end-of-day market data. They're typically available after market close (4:30 PM GMT). Real-time prices update every 15 minutes.
              </p>
            </div>

            <div>
              <h4 className="font-semibold mb-2">What stocks can I trade?</h4>
              <p className="text-sm text-muted-foreground">
                We cover 212 major stocks including all S&P 500 components, NASDAQ leaders, and popular UK stocks. If a stock isn't available, it may not have sufficient trading volume or data for reliable signals.
              </p>
            </div>

            <div>
              <h4 className="font-semibold mb-2">Can I export my trade history?</h4>
              <p className="text-sm text-muted-foreground">
                Currently, you can view your trade history in the simulator. Export functionality is coming soon. For now, you can take screenshots or manually record your trades.
              </p>
            </div>

            <div>
              <h4 className="font-semibold mb-2">What's the difference between manual and auto-trading?</h4>
              <p className="text-sm text-muted-foreground">
                Manual trading: You decide when to buy/sell based on signals. Auto-trading: The system automatically executes trades based on signals at set intervals. Auto-trading is a premium feature.
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Video Tutorials Section */}
        <Card className="premium-card border-0 bg-transparent shadow-none">
          <CardHeader>
            <div className="flex items-start gap-3">
              <Video className="h-6 w-6 text-primary flex-shrink-0 mt-1" />
              <div>
                <CardTitle className="text-2xl">Video Tutorials</CardTitle>
                <CardDescription className="mt-1">Learn by watching step-by-step video guides</CardDescription>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <VideoPlaylist
              title="Getting Started Series"
              description="Watch these videos to get up and running with Stock Predictor"
              videos={[
                {
                  title: 'Introduction to Trading Signals',
                  description: 'Learn what trading signals are and how they help you make better trading decisions',
                  videoId: 'dQw4w9WgXcQ',
                  duration: '5:32',
                },
                {
                  title: 'Setting Up Your Watchlist',
                  description: 'Step-by-step guide to adding stocks to your watchlist and tracking signals',
                  videoId: 'dQw4w9WgXcQ',
                  duration: '4:15',
                },
                {
                  title: 'Using the Paper Trading Simulator',
                  description: 'Practice trading with virtual money and test your strategies risk-free',
                  videoId: 'dQw4w9WgXcQ',
                  duration: '6:48',
                },
                {
                  title: 'Understanding Technical Indicators',
                  description: 'Deep dive into RSI, MACD, Bollinger Bands, and SMA indicators',
                  videoId: 'dQw4w9WgXcQ',
                  duration: '8:22',
                },
              ]}
            />
          </CardContent>
        </Card>

        {/* CTA */}
        <div className="flex gap-3 justify-center pt-4">
          <Button
            onClick={() => setLocation('/signals')}
            className="pill-button pill-button-primary"
          >
            View Signals Dashboard
          </Button>
          <Button
            onClick={() => setLocation('/simulator')}
            variant="outline"
            className="pill-button"
          >
            Go to Simulator
          </Button>
        </div>
      </div>
    </div>
  );
}
