/**
 * Public "Today's Top Signals" page — /signals/today
 *
 * Fully ungated, SEO-indexed, shareable daily page showing the top
 * AI-generated buy/sell signals from the last 24 hours.
 * Confidence scores are capped at 60 for non-members; full scores
 * are shown to encourage sign-up.
 */

import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { PublicSiteHeader } from "@/components/PublicSiteHeader";
import { useLocation } from "wouter";
import { getLoginUrl } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import {
  TrendingUp,
  TrendingDown,
  ArrowUpRight,
  Zap,
  Clock,
  BarChart3,
  Lock,
  RefreshCw,
} from "lucide-react";
import { useMemo, useState } from "react";
import { Helmet } from "react-helmet-async";

function SignalTypeBadge({ type }: { type: string }) {
  if (type === "buy") {
    return (
      <Badge className="bg-emerald-500/15 text-emerald-400 border-emerald-500/30 font-bold uppercase tracking-wide text-xs">
        <TrendingUp className="h-3 w-3 mr-1" />
        BUY
      </Badge>
    );
  }
  return (
    <Badge className="bg-rose-500/15 text-rose-400 border-rose-500/30 font-bold uppercase tracking-wide text-xs">
      <TrendingDown className="h-3 w-3 mr-1" />
      SELL
    </Badge>
  );
}

function ConfidenceBar({ score, locked }: { score: number; locked?: boolean }) {
  const colour =
    score >= 80
      ? "bg-emerald-500"
      : score >= 65
      ? "bg-amber-400"
      : "bg-rose-400";
  return (
    <div className="flex items-center gap-2">
      {locked ? (
        <Lock className="h-3.5 w-3.5 text-slate-500 shrink-0" />
      ) : null}
      <div className="flex-1 h-1.5 rounded-full bg-slate-700/60 overflow-hidden">
        <div
          className={`h-full rounded-full transition-all ${colour} ${locked ? "opacity-40" : ""}`}
          style={{ width: `${score}%` }}
        />
      </div>
      <span className={`text-xs font-bold tabular-nums ${locked ? "text-slate-500" : "text-slate-300"}`}>
        {locked ? "≤60%" : `${score}%`}
      </span>
    </div>
  );
}

export default function TodaysSignals() {
  const [location] = useLocation();
  const { user } = useAuth();
  const [filter, setFilter] = useState<"all" | "buy" | "sell">("all");

  const { data: rawSignals, isLoading, refetch, isFetching } = trpc.publicSignals.getToday.useQuery(undefined, {
    staleTime: 5 * 60 * 1000, // 5 minutes
  });

  const signals = useMemo(() => {
    if (!rawSignals) return [];
    return rawSignals.filter((s) => filter === "all" || s.type === filter);
  }, [rawSignals, filter]);

  const stats = useMemo(() => {
    if (!rawSignals) return null;
    const buy = rawSignals.filter((s: { type: string }) => s.type === "buy").length;
    const sell = rawSignals.filter((s: { type: string }) => s.type === "sell").length;
    const avgConf = rawSignals.length
      ? Math.round(rawSignals.reduce((a: number, s: { confidenceScore: number }) => a + s.confidenceScore, 0) / rawSignals.length)
      : 0;
    return { buy, sell, total: rawSignals.length, avgConf };
  }, [rawSignals]);

  const today = new Date().toLocaleDateString("en-GB", {
    weekday: "long",
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  return (
    <>
      <Helmet>
        <title>Today's Top AI Trading Signals — {today} | Vortextrade</title>
        <meta
          name="description"
          content={`Free AI-generated buy and sell signals for UK stocks on Trading 212. Updated every 15 minutes. ${stats?.total ?? 0} signals today — see which stocks the AI is watching.`}
        />
        <meta property="og:title" content={`Today's Top Trading Signals — ${today}`} />
        <meta
          property="og:description"
          content={`${stats?.buy ?? 0} buy signals and ${stats?.sell ?? 0} sell signals generated by Vortextrade AI today. Free to view.`}
        />
        <meta property="og:url" content="https://vortextrade.manus.space/signals/today" />
        <link rel="canonical" href="https://vortextrade.manus.space/signals/today" />
      </Helmet>

      <div className="min-h-screen bg-[#0a0f1e]">
        <PublicSiteHeader currentPath={location} />

        {/* Hero */}
        <section className="pt-24 pb-10 px-4 text-center">
          <div className="inline-flex items-center gap-2 rounded-full border border-cyan-500/30 bg-cyan-500/10 px-4 py-1.5 text-sm text-cyan-400 font-medium mb-6">
            <Zap className="h-3.5 w-3.5" />
            Live AI signals · Updated every 15 minutes
          </div>
          <h1 className="text-4xl md:text-5xl font-bold text-white mb-4">
            Today's Top Trading Signals
          </h1>
          <p className="text-slate-400 text-lg max-w-xl mx-auto mb-2">
            AI-generated buy and sell signals for stocks on Trading 212.
            Free to view — no account required.
          </p>
          <p className="text-slate-500 text-sm flex items-center justify-center gap-1.5">
            <Clock className="h-3.5 w-3.5" />
            {today}
          </p>
        </section>

        {/* Stats bar */}
        <div className="max-w-5xl mx-auto px-4 mb-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            {[
              {
                label: "Total signals today",
                value: stats?.total ?? 0,
                icon: <BarChart3 className="h-4 w-4 text-cyan-400" />,
              },
              {
                label: "Buy signals",
                value: stats?.buy ?? 0,
                icon: <TrendingUp className="h-4 w-4 text-emerald-400" />,
              },
              {
                label: "Sell signals",
                value: stats?.sell ?? 0,
                icon: <TrendingDown className="h-4 w-4 text-rose-400" />,
              },
              {
                label: "Avg confidence",
                value: stats ? `${stats.avgConf}%` : "—",
                icon: <Zap className="h-4 w-4 text-amber-400" />,
              },
            ].map((stat) => (
              <Card key={stat.label} className="bg-slate-800/50 border-slate-700/60">
                <CardContent className="pt-4 pb-3">
                  <div className="flex items-center gap-2 mb-1">
                    {stat.icon}
                    <span className="text-slate-400 text-xs">{stat.label}</span>
                  </div>
                  {isLoading ? (
                    <Skeleton className="h-7 w-12" />
                  ) : (
                    <p className="text-white text-xl font-bold">{stat.value}</p>
                  )}
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* Filter + refresh */}
        <div className="max-w-5xl mx-auto px-4 mb-6 flex items-center justify-between flex-wrap gap-3">
          <div className="flex gap-2">
            {(["all", "buy", "sell"] as const).map((f) => (
              <Button
                key={f}
                size="sm"
                variant={filter === f ? "default" : "outline"}
                onClick={() => setFilter(f)}
                className={
                  filter === f
                    ? "bg-cyan-600 hover:bg-cyan-500 text-white border-0"
                    : "border-slate-600 text-slate-300 hover:text-white hover:border-cyan-500 bg-transparent"
                }
              >
                {f === "all" ? "All signals" : f === "buy" ? "Buy only" : "Sell only"}
              </Button>
            ))}
          </div>
          <Button
            size="sm"
            variant="outline"
            onClick={() => refetch()}
            disabled={isFetching}
            className="border-slate-600 text-slate-400 hover:text-white bg-transparent"
          >
            <RefreshCw className={`h-3.5 w-3.5 mr-1.5 ${isFetching ? "animate-spin" : ""}`} />
            Refresh
          </Button>
        </div>

        {/* Signal list */}
        <div className="max-w-5xl mx-auto px-4 pb-16 space-y-3">
          {isLoading ? (
            Array.from({ length: 6 }).map((_, i) => (
              <Skeleton key={i} className="h-24 w-full rounded-2xl" />
            ))
          ) : signals.length === 0 ? (
            <div className="text-center py-16 text-slate-500">
              <BarChart3 className="h-12 w-12 mx-auto mb-4 opacity-30" />
              <p className="text-lg font-medium">No signals yet today</p>
              <p className="text-sm mt-1">Check back in a few minutes — the AI refreshes every 15 minutes.</p>
            </div>
          ) : (
            signals.map((signal) => {
              const isLocked = !user && signal.confidenceScore > 60;
              return (
                <Card
                  key={signal.id}
                  className="bg-slate-800/40 border-slate-700/60 hover:border-slate-600 transition-colors"
                >
                  <CardContent className="p-4 md:p-5">
                    <div className="flex items-start justify-between gap-4">
                      <div className="flex items-center gap-3 min-w-0">
                        <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-slate-700/60 font-bold text-white text-sm">
                          {signal.ticker.slice(0, 4)}
                        </div>
                        <div className="min-w-0">
                          <div className="flex items-center gap-2 flex-wrap">
                            <span className="text-white font-bold text-base">{signal.ticker}</span>
                            <SignalTypeBadge type={signal.type} />
                          </div>
                          <p className="text-slate-400 text-xs mt-0.5">
                            {signal.stockName && <span className="mr-2">{signal.stockName}</span>}
                            {new Date(signal.createdAt).toLocaleTimeString("en-GB", {
                              hour: "2-digit",
                              minute: "2-digit",
                            })}
                          </p>
                        </div>
                      </div>
                      <div className="flex items-center gap-3 shrink-0">
                        {signal.priceAtSignal && (
                          <div className="text-right hidden sm:block">
                            <p className="text-slate-400 text-xs">Price at signal</p>
                            <p className="text-white font-bold text-sm">
                              ${parseFloat(signal.priceAtSignal).toFixed(2)}
                            </p>
                          </div>
                        )}
                      </div>
                    </div>
                    <div className="mt-3">
                      <p className="text-slate-400 text-xs mb-1.5">AI confidence</p>
                      <ConfidenceBar score={signal.confidenceScore} locked={isLocked} />
                    </div>
                    {signal.analysis && !isLocked && (
                      <p className="text-slate-400 text-xs mt-3 line-clamp-2">{signal.analysis}</p>
                    )}
                    {isLocked && (
                      <div className="mt-3 flex items-center justify-between">
                        <p className="text-slate-500 text-xs">
                          Sign in to see the full confidence score and analysis
                        </p>
                        <Button
                          size="sm"
                          className="bg-cyan-600 hover:bg-cyan-500 text-white text-xs h-7 px-3"
                          onClick={() => { window.location.href = getLoginUrl(); }}
                        >
                          Sign in free
                          <ArrowUpRight className="h-3 w-3 ml-1" />
                        </Button>
                      </div>
                    )}
                  </CardContent>
                </Card>
              );
            })
          )}
        </div>

        {/* CTA banner */}
        {!user && (
          <section className="border-t border-slate-800 bg-slate-900/50 py-12 px-4 text-center">
            <h2 className="text-2xl font-bold text-white mb-3">
              Get real-time alerts when signals fire
            </h2>
            <p className="text-slate-400 max-w-md mx-auto mb-6">
              Free members see signals with a 15-minute delay. Sign up free to get instant alerts,
              full confidence scores, and AI analysis for every signal.
            </p>
            <Button
              size="lg"
              className="bg-cyan-600 hover:bg-cyan-500 text-white rounded-full px-8"
              onClick={() => { window.location.href = getLoginUrl(); }}
            >
              Start free — no card required
              <ArrowUpRight className="h-4 w-4 ml-2" />
            </Button>
          </section>
        )}
      </div>
    </>
  );
}
