import React from 'react';
import { Share2, Twitter, MessageCircle, Copy, Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

interface SignalSharingProps {
  signal: {
    ticker: string;
    type: 'buy' | 'sell' | 'hold';
    confidence: number;
    indicators: string[];
  };
  portfolioName?: string;
  onShare?: (platform: string) => void;
}

interface ToastOptions {
  title: string;
  description: string;
}

export function SignalSharing({ signal, portfolioName, onShare }: SignalSharingProps) {
  const [copied, setCopied] = React.useState(false);

  const generateShareText = () => {
    const signalEmoji = signal.type === 'buy' ? '📈' : signal.type === 'sell' ? '📉' : '➡️';
    const text = `${signalEmoji} ${signal.type.toUpperCase()} Signal for $${signal.ticker}
Confidence: ${signal.confidence}%
Indicators: ${signal.indicators.join(', ')}

Generated by Vortextrade - AI-powered trading signals
#trading #stocks #signals`;
    return text;
  };

  const generateShareUrl = () => {
    return `${window.location.origin}/signals?ticker=${signal.ticker}`;
  };

  const shareText = generateShareText();
  const shareUrl = generateShareUrl();

  const handleTwitterShare = () => {
    const text = encodeURIComponent(shareText);
    const url = `https://twitter.com/intent/tweet?text=${text}&url=${encodeURIComponent(shareUrl)}`;
    window.open(url, '_blank', 'width=600,height=400');
    onShare?.('twitter');
  };

  const handleRedditShare = () => {
    const title = `${signal.type.toUpperCase()} Signal: $${signal.ticker} (${signal.confidence}% confidence)`;
    const url = `https://reddit.com/submit?title=${encodeURIComponent(title)}&text=${encodeURIComponent(shareText)}&url=${encodeURIComponent(shareUrl)}`;
    window.open(url, '_blank', 'width=600,height=400');
    onShare?.('reddit');
  };

  const handleDiscordShare = () => {
    const discordText = `**${signal.type.toUpperCase()} Signal: $${signal.ticker}**\n\`\`\`\nConfidence: ${signal.confidence}%\nIndicators: ${signal.indicators.join(', ')}\n\`\`\`\n${shareUrl}`;
    navigator.clipboard.writeText(discordText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    onShare?.('discord');
  };

  const handleCopyLink = () => {
    navigator.clipboard.writeText(shareUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <Card className="premium-card">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Share2 className="h-5 w-5" />
          Share This Signal
        </CardTitle>
        <CardDescription>
          Share this {signal.type} signal with your trading community
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Signal Preview */}
        <div className="bg-secondary/50 rounded-lg p-3 space-y-2">
          <div className="flex items-center justify-between">
            <span className="font-semibold">${signal.ticker}</span>
            <span className="text-sm font-medium capitalize px-2 py-1 rounded bg-primary/20 text-primary">
              {signal.type}
            </span>
          </div>
          <div className="text-sm text-muted-foreground space-y-1">
            <p>Confidence: {signal.confidence}%</p>
            <p>Indicators: {signal.indicators.join(', ')}</p>
          </div>
        </div>

        {/* Share Buttons */}
        <div className="grid grid-cols-2 gap-2">
          <Button
            onClick={handleTwitterShare}
            variant="outline"
            className="gap-2"
            size="sm"
          >
            <Twitter className="h-4 w-4" />
            Twitter
          </Button>
          <Button
            onClick={handleRedditShare}
            variant="outline"
            className="gap-2"
            size="sm"
          >
            <MessageCircle className="h-4 w-4" />
            Reddit
          </Button>
          <Button
            onClick={handleDiscordShare}
            variant="outline"
            className="gap-2"
            size="sm"
          >
            <MessageCircle className="h-4 w-4" />
            Discord
          </Button>
          <Button
            onClick={handleCopyLink}
            variant="outline"
            className="gap-2"
            size="sm"
          >
            {copied ? (
              <>
                <Check className="h-4 w-4" />
                Copied
              </>
            ) : (
              <>
                <Copy className="h-4 w-4" />
                Copy Link
              </>
            )}
          </Button>
        </div>

        {/* Share Text Preview */}
        <div className="bg-secondary/30 rounded-lg p-3">
          <p className="text-xs font-medium text-muted-foreground mb-2">Preview:</p>
          <p className="text-xs text-muted-foreground whitespace-pre-wrap line-clamp-4">
            {shareText}
          </p>
        </div>

        {/* Disclaimer */}
        <p className="text-xs text-muted-foreground">
          Remember: Past performance does not guarantee future results. Always do your own research before trading.
        </p>
      </CardContent>
    </Card>
  );
}

// Hook for tracking signal shares
export function useSignalSharing() {
  const trackShare = (ticker: string, platform: string, confidence: number) => {
    // This would typically send analytics to your backend
    console.log(`Signal shared: ${ticker} on ${platform} (${confidence}% confidence)`);
  };

  return { trackShare };
}
